[global]

    output_filename_prefix = "EMT_ASE"
    random_seed = 5

    max_iter = 50000

    snapshot_interval = 50000

    [global.step_size_tune]

        interval = 1000

[ns]

    n_walkers = 280
    walk_length = 400
    configs_module = "pymatnext.ns_configs.ase_atoms"

[configs]

    composition = "CuAl"
    n_atoms = 16
    initial_rand_vol_per_atom = 800.0
    initial_rand_min_dist = 0.5

    [configs.calculator]

        type = "ASE"
        args.module = "examples.EMT_ASE.EMT"

    [configs.walk]

        gmc_traj_len = 8
        cell_traj_len = 4

        gmc_proportion = 1.0
        cell_proportion = 1.5
        type_proportion = 1.0

        [configs.walk.cell]

            pressure_GPa = 0.1

            [configs.walk.cell.submove_probabilities]
                volume = 0.33
                shear = 0.33
                stretch = 0.33
